### PR TITLE
Separate root and child functions

### PR DESCRIPTION
**Pull request by mcordova47**
Adds a `Wrapper` class, with two instances for root and child wrappers. This way, we can encode into the types whether a function has to run on the root wrapper, like update:

image

I think this should also extend to other things, like:

* Does the function have to run on a single element?
* Shallow vs. Full rendering

But I haven’t thought too much about it, yet.

### CODE REVIEW

**Review by fsoikin — COMMENTED** [review]
While the single/multiple distinction would indeed be useful, I think the root/child distinction doesn't help with anything. Logically, there is no reason functions should work differently between child and root elements, and indeed, in your code only the `update` function actually uses this distinction.

But there is no deep reason that `update` should be prohibited on child elements. It's just an implementation quirk of Enzyme.

From the end user perspective, `update` shouldn't even apply to any element in particular. Rather, it should affect "the world" (or, more precisely, the "current simulation"). 

There is no reason `update` should be prohibited inside a `withSelector`, quite the opposite: it creates an inconvenience. Now I have to exit the `withSelector` context just to call `waitUntil`

Currently `update` simply doesn't work inside a `withSelector`, but instead of explicitly preventing it from being called there, we should make it work. I'm pretty sure there is a way to find the root element by repeatedly calling `parent`, but even failing that, we can solve this by carrying around not just the "current" element, but the original root as well.

**Comment by mcordova47** [comment]
> I'm pretty sure there is a way to find the root element by repeatedly calling `parent`, but even failing that, we can solve this by carrying around not just the "current" element, but the original root as well.

But the problem, I think, is how do you get the updated "current" element -- not just how to get the root.

**Comment by fsoikin** [comment]
Ah, I think there is a bit of misunderstanding here. The `update` function doesn't return an updated root functional-style, it just mutates the internal state of everything. And you can keep using your existing `ElementWrapper` objects, they still point to the same DOM elements.

But here's the kicker: apparently the Enzyme team had the same idea 3 years ago. Check this out: https://github.com/enzymejs/enzyme/pull/1802#discussion_r215566188

And the comment was updated too: https://github.com/enzymejs/enzyme/pull/1802/files#diff-380144706937206c2b8ef0761bb879bc2c25e6cb11b7b31dd0091e5c690f5fddR226

But the docs are apparently out of date now.

**Comment by mcordova47** [comment]
Interesting, but then does that mean this already works?

**Comment by fsoikin** [comment]
Yes, exactly

**Pull request closed without merging**
